name: Daily Update

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update log
        run: |
          echo "## 📅 $(date)" >> log.md
          echo "- Learning something new 🚀" >> log.md
          echo "" >> log.md

      - name: Commit & Push
        run: |
          git config --global user.name "atulXdev"
          git config --global user.email "your-email"
          git add .
          git commit -m "chore: daily update" || echo "No changes"
          git push
